
name: Check

on:
  pull_request:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  elixir: 1.13
  otp: 25

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.elixir }}
          otp-version: ${{ env.otp }}
      - uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: |
          mix deps.get
          mix deps.unlock --check-unused
          mix deps.compile
          mix dialyzer --plt
        if: steps.mix-cache.outputs.cache-hit != 'true'

  static-code-analysis:
    name: Static code analysis
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.elixir }}
          otp-version: ${{ env.otp }}
      - uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: mix format --check-formatted
      - run: mix compile --warnings-as-errors
      - run: mix credo --strict
      - run: mix dialyzer --no-check

  mix-test:
    name: Tests
    needs: dependencies
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.elixir }}
          otp-version: ${{ env.otp }}
      - uses: actions/cache@v3
        id: mix-cache
        with:
          path: |
            _build
            deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - run: |
          mix test --slowest 10 --trace --warnings-as-errors
          mix test --no-start --slowest 10 --trace --warnings-as-errors

  dependabot:
    runs-on: ubuntu-latest
    needs:
      - static-code-analysis
      - mix-test
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
      PR_URL: ${{ github.event.pull_request.html_url }}
    steps:
      - name: Approve a PR
        run: gh pr review -a "$PR_URL"
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto -m "$PR_URL"
